### ISSUE TITLE
Add New Language: JavaScript

### ISSUE THREAD

**Issue by MrKrishnaAgarwal** [MrKrishnaAgarwal/Awesome-Programming-Languages#5]
### Description

JavaScript is often abbreviated JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites use JavaScript on the client side for web page behavior, often incorporating third-party libraries. All major web browsers have a dedicated JavaScript engine to execute the code on users' devices.

**Comment by MrKrishnaAgarwal** [comment]
This is an example issue.

**Comment by Abhay-tech-boy** [comment]
hey
